config/routes.rb
require 'sidekiq/web'
require 'api_constraints'

Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'markers#index'
  devise_for :users, path: :accounts
  mount Sidekiq::Web, at: "/sidekiq"

  resources :users, only: [:index, :destroy]
  resources :markers, only: [:index, :show, :new, :create, :destroy]
  resources :notifications, only: [:index, :create]

  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users, only: [:show, :create]
      resources :markers, only: [:show, :index, :create, :destroy]
      resources :gcms, only: :create
      resources :sessions
    end
  end
end

app/models/marker.rb
class Marker < ActiveRecord::Base
  resourcify

  has_many :marker_users

  mount_uploader :image, AttachmentUploader
  mount_uploader :iset, AttachmentUploader
  mount_uploader :fset, AttachmentUploader
  mount_uploader :fset3, AttachmentUploader
end

app/controllers/api/v1/markers_controller.rb
class Api::V1::MarkersController < ApplicationController
  respond_to :json
  skip_before_action :verify_authenticity_token
  before_action :authenticate_with_token!, only: [:create]

  def index
    @marker_users = MarkerUser.all
  end

  def show
    @marker = Marker.find_by id: params[:id]
  end


  def destroy
    @marker = Marker.find_by id: params[:id]
    @marker_user = MarkerUser.find_by marker_id: params[:id]

    @marker_user.destroy
    @marker.destroy
    render json: { success: "Marker deleted" }, status: 200
  end

  def create
    @current_user_api

    temp = params
    params = {
      :marker => {
      :name => temp["name"],
      :image =>
      {
        :file => temp["base64"],
        :filename => (temp[:name] + ".jpg")
        }
      }
    }
    if params[:marker][:image][:file]
       image_params = params[:marker][:image]
       tempfile = Tempfile.new("fileupload")
       tempfile.binmode
       tempfile.write(Base64.decode64(image_params[:file]))
       uploaded_file = ActionDispatch::Http::UploadedFile.new(:tempfile => tempfile, :filename => image_params[:filename], :original_filename => image_params[:filename])
       params[:marker][:image] =  uploaded_file
    end

    @marker = Marker.new(params[:marker])
    @marker.save
    @marker_user = @current_user_api.marker_users.create(marker_id: @marker.id, content: temp["content"])
    if @marker_user
      GentexdataWorker.perform_async(@marker.id, @marker_user.id)
      @marker_user
    else
      render json: { errors: "Create marker fail" }, status: 200
    end
  end

end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :authenticate_user!

  def index
    @marker_users = MarkerUser.all
  end

  def new
    @marker = Marker.new
  end

  def create
    @marker = Marker.new(marker_params)

    if @marker.save
      marker_user = current_user.marker_users.create(marker_id: @marker.id, content: params["content"])
      GentexdataWorker.perform_async(@marker.id, marker_user.id)
      redirect_to markers_path, notice: "The marker #{@marker.name} has been created."
    else
      render "new"
    end
  end

  def destroy
    @marker_user = MarkerUser.find params[:id]
    @marker = Marker.find_by id: @marker_user.marker_id
    @marker_user.destroy
    @marker.destroy
    redirect_to markers_path
  end

  def show
    @marker = Marker.find_by id: params[:id]
  end

  private
  def marker_params
    params.require(:marker).permit(:name, :image)
  end
end

app/helpers/markers_helper.rb
require 'ffi'

module MarkersHelper
  extend FFI::Library
  ffi_lib 'c'
  ffi_lib 'public/libgenTexData.so'
  attach_function :genTexData, [:string], :void
end

app/views/markers/create.html.erb
<h1>Markers#create</h1>
<p>Find me in app/views/markers/create.html.erb</p>

app/views/markers/destroy.html.erb
<h1>Markers#destroy</h1>
<p>Find me in app/views/markers/destroy.html.erb</p>

app/views/markers/index.html.erb
<div class="site-content" >
  <div class="entry">
    <div class="entry-meta">
      <h3>All markers</h3>
    </div>

    <div class="entry-content">
      <div style="margin-bottom: 10px">
        <%= link_to "New marker", new_marker_path, class: "btn btn-primary" %>
      </div>

      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>User</th>
            <th>Image</th>
            <th>Content</th>
            <th>Available</th>
            <th>Created at</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          <% @marker_users.each do |marker_user| %>
            <tr>
              <td><%= link_to marker_user.marker.id, marker_path(marker_user.marker) %></td>
              <td><%= link_to marker_user.marker.name, marker_path(marker_user.marker) %></td>
              <td><%= marker_user.user.name %></td>
              <td><%= image_tag marker_user.marker.image, size: '150x150' %></td>
              <td><%= marker_user.content %></td>
              <td><%= marker_user.available %></td>
              <td><%= marker_user.created_at %></td>
              <td><%= link_to "Delete", marker_path(marker_user), method: :delete, class: "btn btn-primary" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/markers/new.html.erb
<div class="site-content" >
  <div class="entry">
    <div class="entry-meta">
      <h3>New marker</h3>
    </div>

    <div class="entry-content">
      <%= form_for @marker, html: { multipart: true } do |f| %>
        <%= f.label 'Marker name' %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>
        <%= f.label 'Content' %>
        <%= text_field_tag 'content', nil, class: 'form-control' %>
        <br>
        <%= f.label :image %>
        <%= f.file_field :image %>
        <br>
        <%= f.submit "Save", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/markers/show.html.erb
<div class="site-content" >
  <div class="entry">
    <div class="entry-meta">
      <h3>Information marker</h3>
    </div>

    <div class="entry-content">
      <table class="table table-bordered">
        <tr>
          <th>ID</th>
          <td><%= @marker.id %></td>
        </tr>
        <tr>
          <th>Marker name</th>
          <td><%= @marker.name %></td>
        </tr>
        <tr>
          <th>Image set file</th>
          <td><%= @marker.iset %></td>
        </tr>
        <tr>
          <th>Features set file</th>
          <td><%= @marker.fset %></td>
        </tr>
        <tr>
          <th>Features3 set file</th>
          <td><%= @marker.fset3 %></td>
        </tr>
        <tr>
          <th>Image</th>
          <td><%= image_tag @marker.image, size: '150x150' %></td>
        </tr>
      </table>
      </ul>
    </div>
  </div>
</div>