config/routes.rb
require 'sidekiq/web'
require 'api_constraints'

Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'markers#index'
  devise_for :users, path: :accounts
  mount Sidekiq::Web, at: "/sidekiq"

  resources :users, only: [:index, :destroy]
  resources :markers, only: [:index, :show, :new, :create, :destroy]
  resources :notifications, only: [:index, :create]

  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users, only: [:show, :create]
      resources :markers, only: [:show, :index, :create, :destroy]
      resources :gcms, only: :create
      resources :sessions
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/marker.rb
class Marker < ActiveRecord::Base
  resourcify

  has_many :marker_users

  mount_uploader :image, AttachmentUploader
  mount_uploader :iset, AttachmentUploader
  mount_uploader :fset, AttachmentUploader
  mount_uploader :fset3, AttachmentUploader
end

app/models/marker_user.rb
class MarkerUser < ActiveRecord::Base
  resourcify
  belongs_to :user
  belongs_to :marker
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  
  rolify :before_add => :before_add_method

  def before_add_method(role)
    # do something before it gets added
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :auth_token, uniqueness: true

  before_create :generate_authentication_token!

  has_many :marker_users

  def generate_authentication_token!
    begin
      self.auth_token = Devise.friendly_token
    end while self.class.exists?(auth_token: auth_token)
  end
end

app/controllers/api/v1/gcms_controller.rb
class Api::V1::GcmsController < ApplicationController
  respond_to :json
  skip_before_action :verify_authenticity_token

  def create
    email = params["email"]
    reg_token = params["reg_token"]
    user = User.find_by_email(email)
    if user && user.update(reg_token: reg_token)
      render :json => {error: false}
    else
      render :json => {error: true}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  include Authenticable
  # before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
    end
end

app/controllers/concerns/authenticable.rb
module Authenticable

  def current_user_api
    @current_user_api ||= User.find_by(auth_token: request.headers['Authorization'])
  end

  def authenticate_with_token!
    render json: { errors: "Not authenticated" },
             status: :unauthorized unless current_user_api.present?
  end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :authenticate_user!

  def index
    @marker_users = MarkerUser.all
  end

  def new
    @marker = Marker.new
  end

  def create
    @marker = Marker.new(marker_params)

    if @marker.save
      marker_user = current_user.marker_users.create(marker_id: @marker.id, content: params["content"])
      GentexdataWorker.perform_async(@marker.id, marker_user.id)
      redirect_to markers_path, notice: "The marker #{@marker.name} has been created."
    else
      render "new"
    end
  end

  def destroy
    @marker_user = MarkerUser.find params[:id]
    @marker = Marker.find_by id: @marker_user.marker_id
    @marker_user.destroy
    @marker.destroy
    redirect_to markers_path
  end

  def show
    @marker = Marker.find_by id: params[:id]
  end

  private
  def marker_params
    params.require(:marker).permit(:name, :image)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!
  
  def index

  end

  def create
    reg_tokens = User.pluck(:reg_token)
    send_message(params[:title], params[:body], reg_tokens)
    redirect_to notifications_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end
end

app/helpers/api/v1/gcms_helper.rb
module Api::V1::GcmsHelper
end

app/helpers/api/v1/logins_helper.rb
module Api::V1::LoginsHelper
end

app/helpers/api/v1/register_helper.rb
module Api::V1::RegisterHelper
end

app/helpers/api/v1/sessions_helper.rb
module Api::V1::SessionsHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
require 'gcm'

module ApplicationHelper

  def send_message title, body, reg_tokens
    gcm = GCM.new("AIzaSyDj8o0B-plxM2SurQqQOG75OvKpiU4YaSE")

    registration_ids= reg_tokens

    options = { :data => { :title => title, :body => body } }
    response = gcm.send(registration_ids, options)
  end
end

app/helpers/markers_helper.rb
require 'ffi'

module MarkersHelper
  extend FFI::Library
  ffi_lib 'c'
  ffi_lib 'public/libgenTexData.so'
  attach_function :genTexData, [:string], :void
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://artoolkit.org/">Augmented Reality</a>
    by <a href="http://facebook.com/HIENBX94">Bùi Xuân Hiền</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><%= link_to "News", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <div class="navbar-header" data-navbar="static">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-menu">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">
        Agumented Reality
      </a>
    </div>

    <div class="collapse navbar-collapse navbar-right" id="navbar-menu">
      <ul class="nav navbar-nav" data-navbar="static">
        <li class="">
          <%= link_to "Admin Site", "/admin" %>
        </li>

        <li class="">
          <%= link_to "Sidekiq", sidekiq_web_path %>
        </li>

        <li class="">
          <%= link_to "Notification", notifications_path %>
        </li>
        <li class="">
          <%= link_to "Markers", markers_path %>
        </li>
        <li class="">
          <%= link_to "Users", users_path %>
        </li>

        <% if user_signed_in? %>
          <li class="dropdown" data-navbar="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Profile", "" %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: :DELETE %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AugmentedReality</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-46776658-3', 'auto');
    ga('send', 'pageview');
  </script>

  <div class="container" style="padding-top: 60px">
    <%= yield %>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- vntech -->
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-9138667967829335"
         data-ad-slot="8345468203"
         data-ad-format="auto"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>

    <script type="text/javascript">
        google_ad_client = "ca-pub-9138667967829335";
        google_ad_slot = "5390171800";
        google_ad_width = 300;
        google_ad_height = 600;
    </script>
    <!-- side -->
    <script type="text/javascript"
    src="//pagead2.googlesyndication.com/pagead/show_ads.js">
    </script>

    <%= render 'layouts/footer' %>
  </div>
</body>
</html>